# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SewerageDesigner
                                 A QGIS plugin
 Design sewer systems 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-01-12
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Nelen & Schuurmans
        email                : info@nelen-schuurmans.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .sewerage_designer_dockwidget import SewerageDesignerDockWidget
import os.path

from qgis_connector import pipe_network_from_layer
from sewerage_designer_core.sewerage_designer_classes import BGTInloopTabel

class SewerageDesigner:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SewerageDesigner_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Sewerage Designer')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'SewerageDesigner')
        self.toolbar.setObjectName(u'SewerageDesigner')

        #print "** INITIALIZING SewerageDesigner"

        self.pluginIsActive = False
        self.dockwidget = None
        
        self.sewerage_network = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SewerageDesigner', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/sewerage_designer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Sewerage Designer'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING SewerageDesigner"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD SewerageDesigner"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Sewerage Designer'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
    
    def create_network_from_layers(self):
        
        sewerage_layer = QgsProject.instance().mapLayersByName(QGS_SEWERAGE_LAYER_NAME)
        weir_layer = QgsProject.instance().mapLayersByName(QGS_WEIR_LAYER_NAME)
        pumping_station_layer = QgsProject.instance().mapLayersByName(QGS_PUMPING_STATION_LAYER_NAME)
        outlet_layer = QgsProject.instance().mapLayersByName(QGS_OUTLET_LAYER_NAME)
        self.network = pipe_network_from_layer(pipe_layer=pipe_layer, weir_layer=weir_layer)
        # Check if layers are present and try to create a network using qgis connector
        # Check validity of network (check if weir is present)
        # Check if BGT inlooptabel is present

    def add_elevation_to_network(self):
        """If DEM dropdown changes, calculate elevation for all pipes and write back to layer"""
        if self.sewerage_network is None:
            self.sewerage_network = create_network_from_layers()
            
        dem = self.dockwidget.get_DEM()
        dem_datasource = gdal.Open(dem)
        dem_rasterband = dem_datasource.GetRasterBand(1)
        dem_geotransform = dem_datasource.GetGeoTransform()
        for pipe in self.network.pipes.items():
            pipe.sample_elevation_model(dem_rasterband=dem_rasterband, dem_geotransform=dem_geotransform)
            
        # update qgs layer?
        network_to_layers(self.sewerage_network)

    def compute_connected_surfaces(self):
        """Create a pipe network and calculate the connected surfaces"""
        if self.sewerage_network is None:
            self.sewerage_network = create_network_from_layers()
        
        bgt_inlooptabel_fn = self.dockwidget.get_BGT_inlooptabel()
        bgt_inlooptabel = BGTInloopTabel(bgt_inlooptabel_fn)
        
        for pipe in self.sewerage_network.pipes:
            pipe.determine_connected_surface_area(bgt_inlooptabel)
        
        self.sewerage_network.accumulate_connected_surface_area()
        
        network_to_layers(self.sewerage_network)
        
        # Compute connected surfaces
        # Write values back to QGS layer            
    
    def compute_diameters(self):
        """Compute diameters for the current network and design rainfall event"""
        if self.sewerage_network is None:
            self.sewerage_network = create_network_from_layers()
       
        # Compute diameters
        # Write values back to QGS layer
        
    def validate_depths(self):
        """Check if the computed depths fit the criteria of the minimum cover depth"""
        if self.sewerage_network is None:
            self.sewerage_network = create_network_from_layers()
       
        
       
    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING SewerageDesigner"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = SewerageDesignerDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
            
            # Connect functionality

